/*
 * AdvancedClipboard
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.UUID;
/**
 * ClipboardGetData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-18T07:58:16.953Z[GMT]")
public class ClipboardGetData {
  @SerializedName("contentTypeId")
  private UUID contentTypeId = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("imageContentUrl")
  private String imageContentUrl = null;

  @SerializedName("textContent")
  private String textContent = null;

   /**
   * Get contentTypeId
   * @return contentTypeId
  **/
  @Schema(description = "")
  public UUID getContentTypeId() {
    return contentTypeId;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public UUID getId() {
    return id;
  }

   /**
   * Get imageContentUrl
   * @return imageContentUrl
  **/
  @Schema(description = "")
  public String getImageContentUrl() {
    return imageContentUrl;
  }

   /**
   * Get textContent
   * @return textContent
  **/
  @Schema(description = "")
  public String getTextContent() {
    return textContent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClipboardGetData clipboardGetData = (ClipboardGetData) o;
    return Objects.equals(this.contentTypeId, clipboardGetData.contentTypeId) &&
        Objects.equals(this.id, clipboardGetData.id) &&
        Objects.equals(this.imageContentUrl, clipboardGetData.imageContentUrl) &&
        Objects.equals(this.textContent, clipboardGetData.textContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentTypeId, id, imageContentUrl, textContent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClipboardGetData {\n");
    
    sb.append("    contentTypeId: ").append(toIndentedString(contentTypeId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    imageContentUrl: ").append(toIndentedString(imageContentUrl)).append("\n");
    sb.append("    textContent: ").append(toIndentedString(textContent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
